---
title: "Publications"
---

<br> <br>

[Google Scholar for comprehensive list](https://scholar.google.com/citations?user=Ql2j3FEAAAAJ&hl=en)

<br>

#### Dutch dairy farmers’ perspectives on culling reasons and strategies
PS Kulkarni, MCM Mourits, J Slob, AMB Veldhuis, M Nielen, H Hogeveen, G van Schaik, W Steeneveld
Preventive Veterinary Medicine, (In press),
[View](https://doi.org/10.1016/j.prevetmed.2023.105997)

<br> <br> 

#### Association between dairy farm performance indicators and culling rates under policy driven herd size constraints
PS Kulkarni, MCM Mourits, M Nielen, W Steeneveld
Frontiers in Veterinary Science 10 (10:1062891), 293
[View](https://www.frontiersin.org/articles/10.3389/fvets.2023.1062891/full)

<br> <br> 

#### Survival Analysis of dairy cows in the Netherlands under altering agricultural policy
PS Kulkarni, MCM Mourits, M Nielen, J van den Broek, W Steeneveld
Preventive Veterinary Medicine 193, 105398
[View](https://www.sciencedirect.com/science/article/pii/S0167587721001422)

<br> <br> 

#### On the origin of the genetic variation in infectious disease prevalence: Genetic analysis of disease status versus infections for Digital Dermatitis in Dutch dairy cattle
PS Kulkarni, F Biemans, MCM de Jong, P Bijma
Journal of Animal Breeding and Genetics 138 (6), 629-642
[View](https://onlinelibrary.wiley.com/doi/pdf/10.1111/jbg.12635)

<br> <br> <br>

# Books/ Theses

<br> <br> 

#### Dairy cattle replacement under changing agri-environmental policies
Pranav S. Kulkarni
Wageningen University Publication, PhD thesis (2024) Wageningen
ISBN 978-94-6447-990-4 DOI: 10.18174/642838 
[View/ Download Free](https://escholarship.org/content/qt246298qt/qt246298qt_noSplash_901536be2763fe6084f6b43f7abc9b70.pdf)

